/**
 * Bundle the browser half into the single file DSH loads.
 *
 * The DSH client-bundle contract requires `exports["./client"]` to be a plain
 * script that calls
 *
 *     window.__ModuleLoader__.load({ id, factory })
 *
 * and whose factory returns `module.exports` exposing `apply` (+ `inject`).
 * The official toolchain for that is tsdown; this repository is
 * dependency-free, so `tsc -p src/client/tsconfig.json` compiles `src/client/**`
 * to **CommonJS** (one file per source module) and this script wraps those files
 * in a ~15-line `require` registry. Two properties make that safe:
 *
 *   - `tsc` performs the ESM→CJS transform, so no parser is needed here;
 *   - relative specifiers are emitted verbatim (`require("./api")`), which is
 *     exactly the registry key.
 *
 * `ORDER` only controls the textual order of the emitted modules. It is
 * load-bearing for one thing beyond readability: the `mcp` dictionaries must
 * precede `api`, so the region after `/* ---- ./api ---- *\/` stays free of Han
 * literals. That is what `test/client-language.test.mjs` asserts.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const partsDir = join(root, 'build', 'client-parts')
const outFile = join(root, 'lib', 'client.js')

/** Module id → compiled part, in textual bundle order. `entry` must be last. */
const ORDER = [
  'types',
  'styles',
  'i18n.zh',
  'i18n.en',
  'api',
  'components/ServerRow',
  'components/ServerForm',
  'components/WorkspaceServerRow',
  'components/GlobalMaskRow',
  'components/McpContent',
  'plugin',
  'entry',
]

const ENTRY = './entry'
const pkg = require(join(root, 'package.json'))

if (!existsSync(partsDir)) {
  console.error(`build-client: ${partsDir} is missing — run \`tsc -p src/client/tsconfig.json\` first`)
  process.exit(1)
}

const definitions = ORDER.map((name) => {
  const part = join(partsDir, `${name}.js`)
  if (!existsSync(part)) {
    console.error(`build-client: compiled part ${name}.js not found in ${partsDir}`)
    process.exit(1)
  }
  const id = `./${name}`
  const body = readFileSync(part, 'utf8')
    .trimEnd()
    .replace(/^/gm, '\t\t\t')
  return `\t\t/* ---- ${id} ---- */\n\t\t${JSON.stringify(id)}: function (module, exports, require) {\n${body}\n\t\t},`
})

const bundle = `/*
 * ${pkg.name} — browser half.
 *
 * GENERATED by scripts/build-client.mjs. Do not edit this file: edit the
 * TypeScript sources under src/client/ and re-run \`pnpm build\`.
 */
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(pkg.name)},
\tfactory: (require) => {
\t\tconst modules = {
${definitions.join('\n')}
\t\t};
\t\tconst cache = {};
\t\t// Relative specifiers are resolved against the *importing* module, exactly
\t\t// like a real loader, so a component may require its siblings by bare name.
\t\tfunction resolve(id, from) {
\t\t\tconst segments = (from.slice(0, from.lastIndexOf("/")) + "/" + id.replace(/\\.js$/, "")).split("/");
\t\t\tconst out = [];
\t\t\tfor (const segment of segments) {
\t\t\t\tif (segment === "" || segment === ".") continue;
\t\t\t\tif (segment === "..") out.pop();
\t\t\t\telse out.push(segment);
\t\t\t}
\t\t\treturn "./" + out.join("/");
\t\t}
\t\tfunction requireFrom(from) {
\t\t\treturn (id) => (typeof id === "string" && id.charAt(0) === "." ? load(resolve(id, from)) : require(id));
\t\t}
\t\tfunction load(key) {
\t\t\tconst cached = cache[key];
\t\t\tif (cached) return cached.exports;
\t\t\tconst define = modules[key];
\t\t\tif (!define) throw new Error(${JSON.stringify(pkg.name)} + ": unknown client module " + key);
\t\t\tconst module = { exports: {} };
\t\t\tcache[key] = module;
\t\t\tdefine(module, module.exports, requireFrom(key));
\t\t\treturn module.exports;
\t\t}
\t\treturn load(${JSON.stringify(ENTRY)});
\t}
});
`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, bundle)

for (const marker of ['window.__ModuleLoader__.load', `id: ${JSON.stringify(pkg.name)}`, `load(${JSON.stringify(ENTRY)})`]) {
  if (!bundle.includes(marker)) {
    console.error(`build-client: the bundle is missing ${marker}`)
    process.exit(1)
  }
}

console.log(`build-client: wrote lib/client.js (${ORDER.length} modules, ${bundle.length} bytes)`)
